//************** Memories ***************** */
export let FETCH_MEMORIES = "FETCH_MEMORIES";
export let FETCH_MEMORIES_SUCCESS = "FETCH_MEMORIES_SUCCESS";
export let FETCH_MEMORIES_FAILED = "FETCH_MEMORIES_FAILED";

export let CREATE_MEMORY = "CREATE_MEMORY";
export let CREATE_MEMORY_SUCCESS = "CREATE_MEMORY_SUCCESS";
export let CREATE_MEMORY_FAILED = "CREATE_MEMORY_FAILED";

export let FETCH_SINGLE_MEMORY = "FETCH_SINGLE_MEMORY";
export let FETCH_SINGLE_MEMORY_SUCCESS = "FETCH_SINGLE_MEMORY_SUCCESS";
export let FETCH_SINGLE_MEMORY_FAILED = "FETCH_SINGLE_MEMORY_FAILED";
export let UPDATE_MEMORY = "UPDATE_MEMORY";
export let UPDATE_MEMORY_SUCCESS = "UPDATE_MEMORY_SUCCESS";
export let UPDATE_MEMORY_FAILED = "UPDATE_MEMORY_FAILED";

export let UPDATE_REVIEW = "UPDATE_REVIEW";
export let UPDATE_REVIEW_FAILED = "UPDATE_REVIEW_FAILED";

export let DELETE_REVIEW = "DELETE_REVIEW";
export let DELETE_REVIEW_FAILED = "DELETE_REVIEW_FAILED";

export let CREATE_REVIEW = "CREATE_REVIEW";
export let CREATE_REVIEW_FAILED = "CREATE_REVIEW_FAILED";

export let RESET_ERRORS = "RESET_ERRORS";

export let DELETE_MEMORY = "DELETE_MEMORY";
export let DELETE_MEMORY_SUCCESS = "DELETE_MEMORY_SUCCESS";

//***************** AUTH ************************* */

export let SIGN_UP = "SIGN_UP";
export let SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export let SIGN_UP_FAILED = "SIGN_UP_FAILED";

export let SIGN_IN = "SIGN_IN";
export let SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export let SIGN_IN_FAILED = "SIGN_IN_FAILED";

export let LOGOUT = "LOGOUT";
